name: Build and Test Validation

on: 
    push:
    pull_request:
        branches: [ main ]
    
jobs:
  build_and_test_validation:
    name: build-and-test-validation-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Node Setup
      uses: actions/setup-node@v4
      with:
        node-version: latest

    - name: Setup and Build Validation
      run: |
        cd client  
        npm install
        npm run build
        npx playwright install
        npm run test
